export const PIZEL_BOTTLE_PREFIX = 'PIZEL_BOTTLE_';

export const PIZEL_BOTTLE_BATTLE_OPTIONS = `${PIZEL_BOTTLE_PREFIX}BATTLE_OPTIONS`;

export const PIZEL_BOTTLE_BATTLE_FIELD = `${PIZEL_BOTTLE_PREFIX}BATTLE_FIELD`;
export const PIZEL_BOTTLE_TEMPLATE_FIELD = `${PIZEL_BOTTLE_PREFIX}TEMPLATE_FIELD`;
